openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0
  description: "Order API to register a customer order for a specific product"
tags:
  - name: "Order"
paths:
  /order/{id}:
    get:
      summary: Get a specific order based on the order's id
      tags:
        - "Order"
      operationId: getOrder
      parameters:
        - in: path
          name: id
          description: "Order's id"
          required: true
          schema:
            type: integer
        - in: header
          name: socialId
          description: "Customer's social id"
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: "Order's id"
                    type: integer
                  status:
                    description: "Order's status (EXECUTED, CANCELED or IN_PROGRESS)"
                    type: string
                  socialId:
                    description: "Customer's id"
                    type: string

        422:
          description: "Order not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Order not found"

        400:
          description: "A required parameter is missing or invalid"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid parameters"
